packages:
  - "apps/*"
  - "!apps/infinite-canvas"
  - "packages/*"
allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  '@ffprobe-installer/darwin-arm64': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  canvas: true
  esbuild: true
  gl: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
